### ISSUE TITLE
Queries are not executed in parallel

### ISSUE THREAD

**Issue by rawagner** [graph-gophers/graphql-transport-ws#14]
Incoming queries/mutations via WS are not executed in parallel.
The code which evaluates the request https://github.com/graph-gophers/graphql-transport-ws/blob/master/graphqlws/internal/connection/connection.go#L187 is executed outside of goroutine which means that every incoming request have to wait for the previous one to finish.
This really slows down execution if the resolver is doing something which takes a long time (like http requests)

**Comment by remorses** [comment]
readLoop is called inside an http handler, that means it is run in parallel with other requests

**Comment by rawagner** [comment]
Correct me if Im wrong but to me, its seems there's one `readLoop` per WS connection. If I send many queries via one WS, all of those queries are read by one `readLoop`. The `readLoop` executes queries one by on here https://github.com/graph-gophers/graphql-transport-ws/blob/master/graphqlws/internal/connection/connection.go#L187 which is happening outside of goroutine.

**Comment by rawagner** [comment]
> `readLoop` is called inside an http handler, that means it is run in parallel with other requests

Ok, I think that actually does not contradict what Im saying.
Im talking about queries sent via one WS - Im seeing that a query has to finish before the following one is read & executed

**Comment by remorses** [comment]
You are right, if a client starts multiple graphql subscriptions in the same WebSocket it will block
 
We should also pass the right cancel and ctx to the goroutine closure because of this issue https://blog.cloudflare.com/a-go-gotcha-when-closures-and-goroutines-collide/

Now if a client starts 2 subscriptions simultaneously it could happen that the goroutine receives only the last cancel and opCtx

**Comment by rawagner** [comment]
Im not very proficient in go but after reading the blog and other sources, it seems that the issue is happening only with variables declared in `for` declaration, not inside. `opCtx` and `cancel` are defined inside so it should be fine.. ? 

`i` is problematic, `y` is not.
```
for i := 0; i < 10; i++ {
   y := i
    go func(i int) {
        fmt.Println(i)
    }(i)
}
```

**Comment by clee** [comment]
@rawagner Yes, this is because of how Go resolves the variable lookups. If you want it to actually get the values at the time of each iteration of the `for` loop, you have to do something like this:

```golang
for i := 0; i < 10; i++ {
    y := i
    go func(a, b int) {
        fmt.Println(a)
        fmt.Println(b)
    }(y, i)
}
```

See http://golang.org/doc/faq#closures_and_goroutines for more detail.

**Comment by rawagner** [comment]
@clee yes, that's basically what I wrote above - we dont have to pass variable to the roroutine if its defined inside the loop. This works fine too
```
for i := 0; i < 10; i++ {
    y := i
    go func(a int) {
        fmt.Println(a)
        fmt.Println(y)
    }(i)
}
```
according to the link you posted - the last example there. So I think that [the PR](https://github.com/graph-gophers/graphql-transport-ws/pull/15) is fine and doesn't need any adjustments regarding the variables in goroutine.
