### ISSUE TITLE
Mention the subscription resolver expected return type on readme

### ISSUE THREAD

**Issue by 0xbhagwan** [graph-gophers/graphql-transport-ws#29]
Hi, when first trying to use and setup this library, before dealing with channels, I tried to implement a minimal example with a simple subscription returning a primitive type.

This resulted is a panic error when reflect was called at ``~/go/src/github.com/graph-gophers/graphql-go/internal/exec/subscribe.go:94`` at runtime only when receiving a subscription query.

This was fixed when I changed the return type to a channel, as it can be seen in the linked example. But I wasted some time looking for the cause of the error (I thought there was an issue with my websocket connection).  I think the README would benefit from including this important requirement, and even better would be to throw errors at compile time when a subscription resolver does not return a channel.

**Comment by pavelnikolov** [comment]
There is already link in the readme to a full example
