### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by sagikazarmark** [graph-gophers/graphql-transport-ws#30]
There is no license attached to this repo which makes using it a bit problematic.

Can you please add a license to the project?

Thanks!

**Comment by ccamel** [comment]
Same request for me. I'm using [FOSSA](https://app.fossa.com) for one of my open-source project and it complains about the absence of a license for this project.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/9574336/113553020-56c2cd80-95f7-11eb-8664-4764fbcf138e.png">

Not a big issue though, but it would be great to have a license added to the project.

Many thanks.

**Comment by pavelnikolov** [comment]
Thank you @ccamel and @sagikazarmark. I just added the license file.
