### ISSUE TITLE
Better option

### ISSUE THREAD

**Issue by Hongbo-Miao** [graph-gophers/graphql-transport-ws#32]
Today in JavaScript world, [graphql-ws](https://github.com/enisdenjo/graphql-ws) is better option than [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws).
Just FYI 🙂

**Comment by pavelnikolov** [comment]
Closing as not related

**Comment by dinvlad** [comment]
Could you please let us know if [the new protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) could be supported by this library in the future?

**Comment by pavelnikolov** [comment]
@dinvlad, this library is 100% protocol agnostic. You could use it with any protocol you want. For the subscriptions this library uses golang channels. This means that it is up to you how to handle the communication with the client. Feel free to create a custom middleware that would upgrade HTTP connections to WebSocket protocol or any other protocol. This project is just a reference implementation with the WS + Go + graph-gophers/graphql-go.
