### ISSUE TITLE
Can't send Keep Alive message from client

### ISSUE THREAD

**Issue by mbuyan** [graph-gophers/graphql-transport-ws#4]
When i try send "keep alive" message from browser there is an error message in response:
↑ {"type":"ka","payload":{}}
↓ {"payload":{"message":"unknown operation message of type: ka"},"type":"error"}

There is no 'typeConnectionKeepAlive' case in [code](https://github.com/graph-gophers/graphql-transport-ws/blob/master/graphqlws/internal/connection/connection.go#L140) .

**Comment by sheldoncoupeheure** [comment]
This issue should be closed, as the pull request was merged.
